/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const $fetch: typeof import('ofetch').$fetch
  const EffectScope: typeof import('vue').EffectScope
  const avatarGroupInjectionKey: typeof import('./node_modules/@nuxt/ui/dist/runtime/composables/useAvatarGroup.js').avatarGroupInjectionKey
  const computed: typeof import('vue').computed
  const createApp: typeof import('vue').createApp
  const customRef: typeof import('vue').customRef
  const defineAsyncComponent: typeof import('vue').defineAsyncComponent
  const defineComponent: typeof import('vue').defineComponent
  const defineLocale: typeof import('./node_modules/@nuxt/ui/dist/runtime/composables/defineLocale.js').defineLocale
  const definePageMeta: typeof import('./src/composables/definePageMeta').definePageMeta
  const defineShortcuts: typeof import('./node_modules/@nuxt/ui/dist/runtime/composables/defineShortcuts.js').defineShortcuts
  const defineStore: typeof import('pinia').defineStore
  const effectScope: typeof import('vue').effectScope
  const extendLocale: typeof import('./node_modules/@nuxt/ui/dist/runtime/composables/defineLocale.js').extendLocale
  const extractShortcuts: typeof import('./node_modules/@nuxt/ui/dist/runtime/composables/defineShortcuts.js').extractShortcuts
  const extractYouTubeVideoId: typeof import('./src/shared/utils/youtube').extractYouTubeVideoId
  const fieldGroupInjectionKey: typeof import('./node_modules/@nuxt/ui/dist/runtime/composables/useFieldGroup.js').fieldGroupInjectionKey
  const formBusInjectionKey: typeof import('./node_modules/@nuxt/ui/dist/runtime/composables/useFormField.js').formBusInjectionKey
  const formErrorsInjectionKey: typeof import('./node_modules/@nuxt/ui/dist/runtime/composables/useFormField.js').formErrorsInjectionKey
  const formFieldInjectionKey: typeof import('./node_modules/@nuxt/ui/dist/runtime/composables/useFormField.js').formFieldInjectionKey
  const formInputsInjectionKey: typeof import('./node_modules/@nuxt/ui/dist/runtime/composables/useFormField.js').formInputsInjectionKey
  const formLoadingInjectionKey: typeof import('./node_modules/@nuxt/ui/dist/runtime/composables/useFormField.js').formLoadingInjectionKey
  const formOptionsInjectionKey: typeof import('./node_modules/@nuxt/ui/dist/runtime/composables/useFormField.js').formOptionsInjectionKey
  const formStateInjectionKey: typeof import('./node_modules/@nuxt/ui/dist/runtime/composables/useFormField.js').formStateInjectionKey
  const generateYouTubeIframe: typeof import('./src/shared/utils/youtube').generateYouTubeIframe
  const getAdminMobileNavigation: typeof import('./src/composables/useAdminNavigation').getAdminMobileNavigation
  const getAdminSidebarNavigation: typeof import('./src/composables/useAdminNavigation').getAdminSidebarNavigation
  const getApiBase: typeof import('./src/composables/useRuntimeConfig').getApiBase
  const getCurrentInstance: typeof import('vue').getCurrentInstance
  const getCurrentScope: typeof import('vue').getCurrentScope
  const getCurrentWatcher: typeof import('vue').getCurrentWatcher
  const getSocketUrl: typeof import('./src/composables/useRuntimeConfig').getSocketUrl
  const getYouTubeEmbedUrl: typeof import('./src/shared/utils/youtube').getYouTubeEmbedUrl
  const h: typeof import('vue').h
  const inject: typeof import('vue').inject
  const inputIdInjectionKey: typeof import('./node_modules/@nuxt/ui/dist/runtime/composables/useFormField.js').inputIdInjectionKey
  const isProxy: typeof import('vue').isProxy
  const isReactive: typeof import('vue').isReactive
  const isReadonly: typeof import('vue').isReadonly
  const isRef: typeof import('vue').isRef
  const isShallow: typeof import('vue').isShallow
  const kbdKeysMap: typeof import('./node_modules/@nuxt/ui/dist/runtime/composables/useKbd.js').kbdKeysMap
  const localeContextInjectionKey: typeof import('./node_modules/@nuxt/ui/dist/runtime/composables/useLocale.js').localeContextInjectionKey
  const markRaw: typeof import('vue').markRaw
  const navigateTo: typeof import('./src/composables/navigateTo').navigateTo
  const nextTick: typeof import('vue').nextTick
  const onActivated: typeof import('vue').onActivated
  const onBeforeMount: typeof import('vue').onBeforeMount
  const onBeforeRouteLeave: typeof import('vue-router').onBeforeRouteLeave
  const onBeforeRouteUpdate: typeof import('vue-router').onBeforeRouteUpdate
  const onBeforeUnmount: typeof import('vue').onBeforeUnmount
  const onBeforeUpdate: typeof import('vue').onBeforeUpdate
  const onDeactivated: typeof import('vue').onDeactivated
  const onErrorCaptured: typeof import('vue').onErrorCaptured
  const onMounted: typeof import('vue').onMounted
  const onRenderTracked: typeof import('vue').onRenderTracked
  const onRenderTriggered: typeof import('vue').onRenderTriggered
  const onScopeDispose: typeof import('vue').onScopeDispose
  const onServerPrefetch: typeof import('vue').onServerPrefetch
  const onUnmounted: typeof import('vue').onUnmounted
  const onUpdated: typeof import('vue').onUpdated
  const onWatcherCleanup: typeof import('vue').onWatcherCleanup
  const portalTargetInjectionKey: typeof import('./node_modules/@nuxt/ui/dist/runtime/composables/usePortal.js').portalTargetInjectionKey
  const provide: typeof import('vue').provide
  const reactive: typeof import('vue').reactive
  const readonly: typeof import('vue').readonly
  const ref: typeof import('vue').ref
  const renderSpotifyEmbed: typeof import('./src/shared/utils/spotify').renderSpotifyEmbed
  const renderYouTubeEmbed: typeof import('./src/shared/utils/youtube').renderYouTubeEmbed
  const resolveComponent: typeof import('vue').resolveComponent
  const shallowReactive: typeof import('vue').shallowReactive
  const shallowReadonly: typeof import('vue').shallowReadonly
  const shallowRef: typeof import('vue').shallowRef
  const storeToRefs: typeof import('pinia').storeToRefs
  const toRaw: typeof import('vue').toRaw
  const toRef: typeof import('vue').toRef
  const toRefs: typeof import('vue').toRefs
  const toValue: typeof import('vue').toValue
  const toastMaxInjectionKey: typeof import('./node_modules/@nuxt/ui/dist/runtime/composables/useToast.js').toastMaxInjectionKey
  const triggerRef: typeof import('vue').triggerRef
  const unref: typeof import('vue').unref
  const useAnimate: typeof import('./src/composables/useAnimate').useAnimate
  const useApi: typeof import('./src/composables/useApi').useApi
  const useAppConfig: typeof import('./node_modules/@nuxt/ui/dist/runtime/vue/composables/useAppConfig.js').useAppConfig
  const useAppMutation: typeof import('./src/composables/queries').useAppMutation
  const useAppQuery: typeof import('./src/composables/queries').useAppQuery
  const useAppStore: typeof import('./src/stores/app').useAppStore
  const useAttrs: typeof import('vue').useAttrs
  const useAuthStore: typeof import('./src/stores/auth').useAuthStore
  const useAuthenticatedFetch: typeof import('./src/composables/useAuthenticatedFetch').useAuthenticatedFetch
  const useAvatarGroup: typeof import('./node_modules/@nuxt/ui/dist/runtime/composables/useAvatarGroup.js').useAvatarGroup
  const useBell: typeof import('./src/composables/useBell').useBell
  const useBookingAlert: typeof import('./src/composables/useBookingAlert').useBookingAlert
  const useColorMode: typeof import('@vueuse/core').useColorMode
  const useComponentIcons: typeof import('./node_modules/@nuxt/ui/dist/runtime/composables/useComponentIcons.js').useComponentIcons
  const useContentSearch: typeof import('./node_modules/@nuxt/ui/dist/runtime/composables/useContentSearch.js').useContentSearch
  const useCreateHotelMutation: typeof import('./src/composables/useHotels').useCreateHotelMutation
  const useCssModule: typeof import('vue').useCssModule
  const useCssVars: typeof import('vue').useCssVars
  const useFieldGroup: typeof import('./node_modules/@nuxt/ui/dist/runtime/composables/useFieldGroup.js').useFieldGroup
  const useFileUpload: typeof import('./node_modules/@nuxt/ui/dist/runtime/composables/useFileUpload.js').useFileUpload
  const useFormField: typeof import('./node_modules/@nuxt/ui/dist/runtime/composables/useFormField.js').useFormField
  const useFormFileUpload: typeof import('./src/composables/useFormFileUpload').useFormFileUpload
  const useHead: typeof import('@unhead/vue').useHead
  const useHotelsQuery: typeof import('./src/composables/useHotels').useHotelsQuery
  const useId: typeof import('vue').useId
  const useKbd: typeof import('./node_modules/@nuxt/ui/dist/runtime/composables/useKbd.js').useKbd
  const useLocale: typeof import('./node_modules/@nuxt/ui/dist/runtime/composables/useLocale.js').useLocale
  const useLocations: typeof import('./src/composables/useLocations').useLocations
  const useModel: typeof import('vue').useModel
  const useNavigation: typeof import('./src/composables/useNavigation').useNavigation
  const useNotificationListener: typeof import('./src/composables/useNotificationListener').useNotificationListener
  const useNotificationsStore: typeof import('./src/stores/notifications').useNotificationsStore
  const useOverlay: typeof import('./node_modules/@nuxt/ui/dist/runtime/composables/useOverlay.js').useOverlay
  const usePlatformApi: typeof import('./src/composables/usePlatformApi').usePlatformApi
  const usePortal: typeof import('./node_modules/@nuxt/ui/dist/runtime/composables/usePortal.js').usePortal
  const useProfileSocket: typeof import('./src/composables/useProfileSocket').useProfileSocket
  const useR2Upload: typeof import('./src/composables/useR2Upload').useR2Upload
  const useResizable: typeof import('./node_modules/@nuxt/ui/dist/runtime/composables/useResizable.js').useResizable
  const useRoute: typeof import('vue-router').useRoute
  const useRouter: typeof import('vue-router').useRouter
  const useRuntimeConfig: typeof import('./src/composables/useRuntimeConfig').useRuntimeConfig
  const useScrollspy: typeof import('./node_modules/@nuxt/ui/dist/runtime/composables/useScrollspy.js').useScrollspy
  const useSecureTokenStorage: typeof import('./src/composables/useSecureTokenStorage').useSecureTokenStorage
  const useSeoMeta: typeof import('@unhead/vue').useSeoMeta
  const useSettings: typeof import('./src/composables/useSettings').useSettings
  const useSettingsStore: typeof import('./src/stores/settings').useSettingsStore
  const useSlots: typeof import('vue').useSlots
  const useSocket: typeof import('./src/composables/useSocket').useSocket
  const useSocketEventBridge: typeof import('./src/composables/useSocketEventBridge').useSocketEventBridge
  const useStatusColor: typeof import('./src/composables/useStatusColor').useStatusColor
  const useStatusLabel: typeof import('./src/composables/useStatusColor').useStatusLabel
  const useTemplateRef: typeof import('vue').useTemplateRef
  const useToast: typeof import('./node_modules/@nuxt/ui/dist/runtime/composables/useToast.js').useToast
  const useVueRouter: typeof import('./src/composables/useVueRouter').useVueRouter
  const useWelcomeListener: typeof import('./src/composables/useWelcomeListener').useWelcomeListener
  const watch: typeof import('vue').watch
  const watchEffect: typeof import('vue').watchEffect
  const watchPostEffect: typeof import('vue').watchPostEffect
  const watchSyncEffect: typeof import('vue').watchSyncEffect
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Component, Slot, Slots, ComponentPublicInstance, ComputedRef, DirectiveBinding, ExtractDefaultPropTypes, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, ShallowRef, MaybeRef, MaybeRefOrGetter, VNode, WritableComputedRef } from 'vue'
  import('vue')
  // @ts-ignore
  export type { ApiError, CallOptions } from './src/composables/useApi'
  import('./src/composables/useApi')
  // @ts-ignore
  export type { BookingAlertData } from './src/composables/useBookingAlert'
  import('./src/composables/useBookingAlert')
  // @ts-ignore
  export type { FileUploadKey } from './src/composables/useFormFileUpload'
  import('./src/composables/useFormFileUpload')
  // @ts-ignore
  export type { Hotel } from './src/composables/useHotels'
  import('./src/composables/useHotels')
  // @ts-ignore
  export type { LocationOption } from './src/composables/useLocations'
  import('./src/composables/useLocations')
  // @ts-ignore
  export type { SignParams, UploadProgress, PendingUploadStatus, PendingUpload } from './src/composables/useR2Upload'
  import('./src/composables/useR2Upload')
  // @ts-ignore
  export type { UpdateHotelSettingsPayload, UpdateProfilePayload, UpdateNotificationPayload, UpdateSecurityPayload } from './src/composables/useSettings'
  import('./src/composables/useSettings')
  // @ts-ignore
  export type { AuthUser, GeoNode, PermissionDetail, HotelPlanDetails, HotelSubscriptionDetails, AssociatedHotel, AuthProfile, LoginResponse, AuthSession } from './src/stores/auth'
  import('./src/stores/auth')
  // @ts-ignore
  export type { InboxNotification, BackendNotification } from './src/stores/notifications'
  import('./src/stores/notifications')
  // @ts-ignore
  export type { HotelSettings, ProfileSettings, BillingPlan, BillingSettings, NotificationChannel, NotificationSettings, SecuritySettings, SettingsState } from './src/stores/settings'
  import('./src/stores/settings')
  // @ts-ignore
  export type { ShortcutConfig, ShortcutsConfig, ShortcutsOptions } from './node_modules/@nuxt/ui/dist/runtime/composables/defineShortcuts.d'
  import('./node_modules/@nuxt/ui/dist/runtime/composables/defineShortcuts.d')
  // @ts-ignore
  export type { UseComponentIconsProps } from './node_modules/@nuxt/ui/dist/runtime/composables/useComponentIcons.d'
  import('./node_modules/@nuxt/ui/dist/runtime/composables/useComponentIcons.d')
  // @ts-ignore
  export type { UseFileUploadOptions } from './node_modules/@nuxt/ui/dist/runtime/composables/useFileUpload.d'
  import('./node_modules/@nuxt/ui/dist/runtime/composables/useFileUpload.d')
  // @ts-ignore
  export type { KbdKey, KbdKeySpecific } from './node_modules/@nuxt/ui/dist/runtime/composables/useKbd.d'
  import('./node_modules/@nuxt/ui/dist/runtime/composables/useKbd.d')
  // @ts-ignore
  export type { OverlayOptions, Overlay } from './node_modules/@nuxt/ui/dist/runtime/composables/useOverlay.d'
  import('./node_modules/@nuxt/ui/dist/runtime/composables/useOverlay.d')
  // @ts-ignore
  export type { UseResizableProps, UseResizableReturn } from './node_modules/@nuxt/ui/dist/runtime/composables/useResizable.d'
  import('./node_modules/@nuxt/ui/dist/runtime/composables/useResizable.d')
  // @ts-ignore
  export type { Toast } from './node_modules/@nuxt/ui/dist/runtime/composables/useToast.d'
  import('./node_modules/@nuxt/ui/dist/runtime/composables/useToast.d')
}

// for vue template auto import
import { UnwrapRef } from 'vue'
declare module 'vue' {
  interface GlobalComponents {}
  interface ComponentCustomProperties {
    readonly $fetch: UnwrapRef<typeof import('ofetch')['$fetch']>
    readonly EffectScope: UnwrapRef<typeof import('vue')['EffectScope']>
    readonly avatarGroupInjectionKey: UnwrapRef<typeof import('./node_modules/@nuxt/ui/dist/runtime/composables/useAvatarGroup.js')['avatarGroupInjectionKey']>
    readonly computed: UnwrapRef<typeof import('vue')['computed']>
    readonly createApp: UnwrapRef<typeof import('vue')['createApp']>
    readonly customRef: UnwrapRef<typeof import('vue')['customRef']>
    readonly defineAsyncComponent: UnwrapRef<typeof import('vue')['defineAsyncComponent']>
    readonly defineComponent: UnwrapRef<typeof import('vue')['defineComponent']>
    readonly defineLocale: UnwrapRef<typeof import('./node_modules/@nuxt/ui/dist/runtime/composables/defineLocale.js')['defineLocale']>
    readonly definePageMeta: UnwrapRef<typeof import('./src/composables/definePageMeta')['definePageMeta']>
    readonly defineShortcuts: UnwrapRef<typeof import('./node_modules/@nuxt/ui/dist/runtime/composables/defineShortcuts.js')['defineShortcuts']>
    readonly defineStore: UnwrapRef<typeof import('pinia')['defineStore']>
    readonly effectScope: UnwrapRef<typeof import('vue')['effectScope']>
    readonly extendLocale: UnwrapRef<typeof import('./node_modules/@nuxt/ui/dist/runtime/composables/defineLocale.js')['extendLocale']>
    readonly extractShortcuts: UnwrapRef<typeof import('./node_modules/@nuxt/ui/dist/runtime/composables/defineShortcuts.js')['extractShortcuts']>
    readonly extractYouTubeVideoId: UnwrapRef<typeof import('./src/shared/utils/youtube')['extractYouTubeVideoId']>
    readonly fieldGroupInjectionKey: UnwrapRef<typeof import('./node_modules/@nuxt/ui/dist/runtime/composables/useFieldGroup.js')['fieldGroupInjectionKey']>
    readonly formBusInjectionKey: UnwrapRef<typeof import('./node_modules/@nuxt/ui/dist/runtime/composables/useFormField.js')['formBusInjectionKey']>
    readonly formErrorsInjectionKey: UnwrapRef<typeof import('./node_modules/@nuxt/ui/dist/runtime/composables/useFormField.js')['formErrorsInjectionKey']>
    readonly formFieldInjectionKey: UnwrapRef<typeof import('./node_modules/@nuxt/ui/dist/runtime/composables/useFormField.js')['formFieldInjectionKey']>
    readonly formInputsInjectionKey: UnwrapRef<typeof import('./node_modules/@nuxt/ui/dist/runtime/composables/useFormField.js')['formInputsInjectionKey']>
    readonly formLoadingInjectionKey: UnwrapRef<typeof import('./node_modules/@nuxt/ui/dist/runtime/composables/useFormField.js')['formLoadingInjectionKey']>
    readonly formOptionsInjectionKey: UnwrapRef<typeof import('./node_modules/@nuxt/ui/dist/runtime/composables/useFormField.js')['formOptionsInjectionKey']>
    readonly formStateInjectionKey: UnwrapRef<typeof import('./node_modules/@nuxt/ui/dist/runtime/composables/useFormField.js')['formStateInjectionKey']>
    readonly generateYouTubeIframe: UnwrapRef<typeof import('./src/shared/utils/youtube')['generateYouTubeIframe']>
    readonly getAdminMobileNavigation: UnwrapRef<typeof import('./src/composables/useAdminNavigation')['getAdminMobileNavigation']>
    readonly getAdminSidebarNavigation: UnwrapRef<typeof import('./src/composables/useAdminNavigation')['getAdminSidebarNavigation']>
    readonly getApiBase: UnwrapRef<typeof import('./src/composables/useRuntimeConfig')['getApiBase']>
    readonly getCurrentInstance: UnwrapRef<typeof import('vue')['getCurrentInstance']>
    readonly getCurrentScope: UnwrapRef<typeof import('vue')['getCurrentScope']>
    readonly getCurrentWatcher: UnwrapRef<typeof import('vue')['getCurrentWatcher']>
    readonly getSocketUrl: UnwrapRef<typeof import('./src/composables/useRuntimeConfig')['getSocketUrl']>
    readonly getYouTubeEmbedUrl: UnwrapRef<typeof import('./src/shared/utils/youtube')['getYouTubeEmbedUrl']>
    readonly h: UnwrapRef<typeof import('vue')['h']>
    readonly inject: UnwrapRef<typeof import('vue')['inject']>
    readonly inputIdInjectionKey: UnwrapRef<typeof import('./node_modules/@nuxt/ui/dist/runtime/composables/useFormField.js')['inputIdInjectionKey']>
    readonly isProxy: UnwrapRef<typeof import('vue')['isProxy']>
    readonly isReactive: UnwrapRef<typeof import('vue')['isReactive']>
    readonly isReadonly: UnwrapRef<typeof import('vue')['isReadonly']>
    readonly isRef: UnwrapRef<typeof import('vue')['isRef']>
    readonly isShallow: UnwrapRef<typeof import('vue')['isShallow']>
    readonly kbdKeysMap: UnwrapRef<typeof import('./node_modules/@nuxt/ui/dist/runtime/composables/useKbd.js')['kbdKeysMap']>
    readonly localeContextInjectionKey: UnwrapRef<typeof import('./node_modules/@nuxt/ui/dist/runtime/composables/useLocale.js')['localeContextInjectionKey']>
    readonly markRaw: UnwrapRef<typeof import('vue')['markRaw']>
    readonly navigateTo: UnwrapRef<typeof import('./src/composables/navigateTo')['navigateTo']>
    readonly nextTick: UnwrapRef<typeof import('vue')['nextTick']>
    readonly onActivated: UnwrapRef<typeof import('vue')['onActivated']>
    readonly onBeforeMount: UnwrapRef<typeof import('vue')['onBeforeMount']>
    readonly onBeforeRouteLeave: UnwrapRef<typeof import('vue-router')['onBeforeRouteLeave']>
    readonly onBeforeRouteUpdate: UnwrapRef<typeof import('vue-router')['onBeforeRouteUpdate']>
    readonly onBeforeUnmount: UnwrapRef<typeof import('vue')['onBeforeUnmount']>
    readonly onBeforeUpdate: UnwrapRef<typeof import('vue')['onBeforeUpdate']>
    readonly onDeactivated: UnwrapRef<typeof import('vue')['onDeactivated']>
    readonly onErrorCaptured: UnwrapRef<typeof import('vue')['onErrorCaptured']>
    readonly onMounted: UnwrapRef<typeof import('vue')['onMounted']>
    readonly onRenderTracked: UnwrapRef<typeof import('vue')['onRenderTracked']>
    readonly onRenderTriggered: UnwrapRef<typeof import('vue')['onRenderTriggered']>
    readonly onScopeDispose: UnwrapRef<typeof import('vue')['onScopeDispose']>
    readonly onServerPrefetch: UnwrapRef<typeof import('vue')['onServerPrefetch']>
    readonly onUnmounted: UnwrapRef<typeof import('vue')['onUnmounted']>
    readonly onUpdated: UnwrapRef<typeof import('vue')['onUpdated']>
    readonly onWatcherCleanup: UnwrapRef<typeof import('vue')['onWatcherCleanup']>
    readonly portalTargetInjectionKey: UnwrapRef<typeof import('./node_modules/@nuxt/ui/dist/runtime/composables/usePortal.js')['portalTargetInjectionKey']>
    readonly provide: UnwrapRef<typeof import('vue')['provide']>
    readonly reactive: UnwrapRef<typeof import('vue')['reactive']>
    readonly readonly: UnwrapRef<typeof import('vue')['readonly']>
    readonly ref: UnwrapRef<typeof import('vue')['ref']>
    readonly renderSpotifyEmbed: UnwrapRef<typeof import('./src/shared/utils/spotify')['renderSpotifyEmbed']>
    readonly renderYouTubeEmbed: UnwrapRef<typeof import('./src/shared/utils/youtube')['renderYouTubeEmbed']>
    readonly resolveComponent: UnwrapRef<typeof import('vue')['resolveComponent']>
    readonly shallowReactive: UnwrapRef<typeof import('vue')['shallowReactive']>
    readonly shallowReadonly: UnwrapRef<typeof import('vue')['shallowReadonly']>
    readonly shallowRef: UnwrapRef<typeof import('vue')['shallowRef']>
    readonly storeToRefs: UnwrapRef<typeof import('pinia')['storeToRefs']>
    readonly toRaw: UnwrapRef<typeof import('vue')['toRaw']>
    readonly toRef: UnwrapRef<typeof import('vue')['toRef']>
    readonly toRefs: UnwrapRef<typeof import('vue')['toRefs']>
    readonly toValue: UnwrapRef<typeof import('vue')['toValue']>
    readonly toastMaxInjectionKey: UnwrapRef<typeof import('./node_modules/@nuxt/ui/dist/runtime/composables/useToast.js')['toastMaxInjectionKey']>
    readonly triggerRef: UnwrapRef<typeof import('vue')['triggerRef']>
    readonly unref: UnwrapRef<typeof import('vue')['unref']>
    readonly useAnimate: UnwrapRef<typeof import('./src/composables/useAnimate')['useAnimate']>
    readonly useApi: UnwrapRef<typeof import('./src/composables/useApi')['useApi']>
    readonly useAppConfig: UnwrapRef<typeof import('./node_modules/@nuxt/ui/dist/runtime/vue/composables/useAppConfig.js')['useAppConfig']>
    readonly useAppMutation: UnwrapRef<typeof import('./src/composables/queries')['useAppMutation']>
    readonly useAppQuery: UnwrapRef<typeof import('./src/composables/queries')['useAppQuery']>
    readonly useAppStore: UnwrapRef<typeof import('./src/stores/app')['useAppStore']>
    readonly useAttrs: UnwrapRef<typeof import('vue')['useAttrs']>
    readonly useAuthStore: UnwrapRef<typeof import('./src/stores/auth')['useAuthStore']>
    readonly useAuthenticatedFetch: UnwrapRef<typeof import('./src/composables/useAuthenticatedFetch')['useAuthenticatedFetch']>
    readonly useAvatarGroup: UnwrapRef<typeof import('./node_modules/@nuxt/ui/dist/runtime/composables/useAvatarGroup.js')['useAvatarGroup']>
    readonly useBell: UnwrapRef<typeof import('./src/composables/useBell')['useBell']>
    readonly useBookingAlert: UnwrapRef<typeof import('./src/composables/useBookingAlert')['useBookingAlert']>
    readonly useColorMode: UnwrapRef<typeof import('@vueuse/core')['useColorMode']>
    readonly useComponentIcons: UnwrapRef<typeof import('./node_modules/@nuxt/ui/dist/runtime/composables/useComponentIcons.js')['useComponentIcons']>
    readonly useContentSearch: UnwrapRef<typeof import('./node_modules/@nuxt/ui/dist/runtime/composables/useContentSearch.js')['useContentSearch']>
    readonly useCreateHotelMutation: UnwrapRef<typeof import('./src/composables/useHotels')['useCreateHotelMutation']>
    readonly useCssModule: UnwrapRef<typeof import('vue')['useCssModule']>
    readonly useCssVars: UnwrapRef<typeof import('vue')['useCssVars']>
    readonly useFieldGroup: UnwrapRef<typeof import('./node_modules/@nuxt/ui/dist/runtime/composables/useFieldGroup.js')['useFieldGroup']>
    readonly useFileUpload: UnwrapRef<typeof import('./node_modules/@nuxt/ui/dist/runtime/composables/useFileUpload.js')['useFileUpload']>
    readonly useFormField: UnwrapRef<typeof import('./node_modules/@nuxt/ui/dist/runtime/composables/useFormField.js')['useFormField']>
    readonly useFormFileUpload: UnwrapRef<typeof import('./src/composables/useFormFileUpload')['useFormFileUpload']>
    readonly useHead: UnwrapRef<typeof import('@unhead/vue')['useHead']>
    readonly useHotelsQuery: UnwrapRef<typeof import('./src/composables/useHotels')['useHotelsQuery']>
    readonly useId: UnwrapRef<typeof import('vue')['useId']>
    readonly useKbd: UnwrapRef<typeof import('./node_modules/@nuxt/ui/dist/runtime/composables/useKbd.js')['useKbd']>
    readonly useLocale: UnwrapRef<typeof import('./node_modules/@nuxt/ui/dist/runtime/composables/useLocale.js')['useLocale']>
    readonly useLocations: UnwrapRef<typeof import('./src/composables/useLocations')['useLocations']>
    readonly useModel: UnwrapRef<typeof import('vue')['useModel']>
    readonly useNavigation: UnwrapRef<typeof import('./src/composables/useNavigation')['useNavigation']>
    readonly useNotificationListener: UnwrapRef<typeof import('./src/composables/useNotificationListener')['useNotificationListener']>
    readonly useNotificationsStore: UnwrapRef<typeof import('./src/stores/notifications')['useNotificationsStore']>
    readonly useOverlay: UnwrapRef<typeof import('./node_modules/@nuxt/ui/dist/runtime/composables/useOverlay.js')['useOverlay']>
    readonly usePlatformApi: UnwrapRef<typeof import('./src/composables/usePlatformApi')['usePlatformApi']>
    readonly usePortal: UnwrapRef<typeof import('./node_modules/@nuxt/ui/dist/runtime/composables/usePortal.js')['usePortal']>
    readonly useProfileSocket: UnwrapRef<typeof import('./src/composables/useProfileSocket')['useProfileSocket']>
    readonly useR2Upload: UnwrapRef<typeof import('./src/composables/useR2Upload')['useR2Upload']>
    readonly useResizable: UnwrapRef<typeof import('./node_modules/@nuxt/ui/dist/runtime/composables/useResizable.js')['useResizable']>
    readonly useRoute: UnwrapRef<typeof import('vue-router')['useRoute']>
    readonly useRouter: UnwrapRef<typeof import('vue-router')['useRouter']>
    readonly useRuntimeConfig: UnwrapRef<typeof import('./src/composables/useRuntimeConfig')['useRuntimeConfig']>
    readonly useScrollspy: UnwrapRef<typeof import('./node_modules/@nuxt/ui/dist/runtime/composables/useScrollspy.js')['useScrollspy']>
    readonly useSecureTokenStorage: UnwrapRef<typeof import('./src/composables/useSecureTokenStorage')['useSecureTokenStorage']>
    readonly useSeoMeta: UnwrapRef<typeof import('@unhead/vue')['useSeoMeta']>
    readonly useSettings: UnwrapRef<typeof import('./src/composables/useSettings')['useSettings']>
    readonly useSettingsStore: UnwrapRef<typeof import('./src/stores/settings')['useSettingsStore']>
    readonly useSlots: UnwrapRef<typeof import('vue')['useSlots']>
    readonly useSocket: UnwrapRef<typeof import('./src/composables/useSocket')['useSocket']>
    readonly useSocketEventBridge: UnwrapRef<typeof import('./src/composables/useSocketEventBridge')['useSocketEventBridge']>
    readonly useStatusColor: UnwrapRef<typeof import('./src/composables/useStatusColor')['useStatusColor']>
    readonly useStatusLabel: UnwrapRef<typeof import('./src/composables/useStatusColor')['useStatusLabel']>
    readonly useTemplateRef: UnwrapRef<typeof import('vue')['useTemplateRef']>
    readonly useToast: UnwrapRef<typeof import('./node_modules/@nuxt/ui/dist/runtime/composables/useToast.js')['useToast']>
    readonly useVueRouter: UnwrapRef<typeof import('./src/composables/useVueRouter')['useVueRouter']>
    readonly useWelcomeListener: UnwrapRef<typeof import('./src/composables/useWelcomeListener')['useWelcomeListener']>
    readonly watch: UnwrapRef<typeof import('vue')['watch']>
    readonly watchEffect: UnwrapRef<typeof import('vue')['watchEffect']>
    readonly watchPostEffect: UnwrapRef<typeof import('vue')['watchPostEffect']>
    readonly watchSyncEffect: UnwrapRef<typeof import('vue')['watchSyncEffect']>
  }
}