/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about': RouteRecordInfo<
      '/about',
      '/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/': RouteRecordInfo<
      '/admin/',
      '/admin',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/bookings/': RouteRecordInfo<
      '/admin/bookings/',
      '/admin/bookings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/bookings/check-ins/': RouteRecordInfo<
      '/admin/bookings/check-ins/',
      '/admin/bookings/check-ins',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/bookings/check-outs/': RouteRecordInfo<
      '/admin/bookings/check-outs/',
      '/admin/bookings/check-outs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/bookings/payments/': RouteRecordInfo<
      '/admin/bookings/payments/',
      '/admin/bookings/payments',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/bookings/reservations/': RouteRecordInfo<
      '/admin/bookings/reservations/',
      '/admin/bookings/reservations',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/bookings/walk-ins/': RouteRecordInfo<
      '/admin/bookings/walk-ins/',
      '/admin/bookings/walk-ins',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/content/': RouteRecordInfo<
      '/admin/content/',
      '/admin/content',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/content/articles/': RouteRecordInfo<
      '/admin/content/articles/',
      '/admin/content/articles',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/content/gallery/': RouteRecordInfo<
      '/admin/content/gallery/',
      '/admin/content/gallery',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/content/social-media/': RouteRecordInfo<
      '/admin/content/social-media/',
      '/admin/content/social-media',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/finance/': RouteRecordInfo<
      '/admin/finance/',
      '/admin/finance',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/finance/banks/': RouteRecordInfo<
      '/admin/finance/banks/',
      '/admin/finance/banks',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/finance/charges/': RouteRecordInfo<
      '/admin/finance/charges/',
      '/admin/finance/charges',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/finance/expenditures/': RouteRecordInfo<
      '/admin/finance/expenditures/',
      '/admin/finance/expenditures',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/finance/hotel-gateways/': RouteRecordInfo<
      '/admin/finance/hotel-gateways/',
      '/admin/finance/hotel-gateways',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/finance/invoices/': RouteRecordInfo<
      '/admin/finance/invoices/',
      '/admin/finance/invoices',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/finance/payouts/': RouteRecordInfo<
      '/admin/finance/payouts/',
      '/admin/finance/payouts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/finance/pos/': RouteRecordInfo<
      '/admin/finance/pos/',
      '/admin/finance/pos',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/finance/refunds/': RouteRecordInfo<
      '/admin/finance/refunds/',
      '/admin/finance/refunds',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/finance/revenues/': RouteRecordInfo<
      '/admin/finance/revenues/',
      '/admin/finance/revenues',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/finance/sales/': RouteRecordInfo<
      '/admin/finance/sales/',
      '/admin/finance/sales',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/finance/subscriptions/': RouteRecordInfo<
      '/admin/finance/subscriptions/',
      '/admin/finance/subscriptions',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/finance/virtual-accounts/': RouteRecordInfo<
      '/admin/finance/virtual-accounts/',
      '/admin/finance/virtual-accounts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/finance/vouchers/': RouteRecordInfo<
      '/admin/finance/vouchers/',
      '/admin/finance/vouchers',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/front-desk': RouteRecordInfo<
      '/admin/front-desk',
      '/admin/front-desk',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/guests/': RouteRecordInfo<
      '/admin/guests/',
      '/admin/guests',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/guests/customers/': RouteRecordInfo<
      '/admin/guests/customers/',
      '/admin/guests/customers',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/guests/directory/': RouteRecordInfo<
      '/admin/guests/directory/',
      '/admin/guests/directory',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/guests/favourites/': RouteRecordInfo<
      '/admin/guests/favourites/',
      '/admin/guests/favourites',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/guests/ratings/': RouteRecordInfo<
      '/admin/guests/ratings/',
      '/admin/guests/ratings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/guests/visitors/': RouteRecordInfo<
      '/admin/guests/visitors/',
      '/admin/guests/visitors',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/insights/': RouteRecordInfo<
      '/admin/insights/',
      '/admin/insights',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/insights/activity-logs/': RouteRecordInfo<
      '/admin/insights/activity-logs/',
      '/admin/insights/activity-logs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/insights/analytics/': RouteRecordInfo<
      '/admin/insights/analytics/',
      '/admin/insights/analytics',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/insights/bookings/': RouteRecordInfo<
      '/admin/insights/bookings/',
      '/admin/insights/bookings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/insights/customers/': RouteRecordInfo<
      '/admin/insights/customers/',
      '/admin/insights/customers',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/insights/exports/': RouteRecordInfo<
      '/admin/insights/exports/',
      '/admin/insights/exports',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/insights/reports/': RouteRecordInfo<
      '/admin/insights/reports/',
      '/admin/insights/reports',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/insights/revenue-trends/': RouteRecordInfo<
      '/admin/insights/revenue-trends/',
      '/admin/insights/revenue-trends',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/operations/': RouteRecordInfo<
      '/admin/operations/',
      '/admin/operations',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/operations/events/': RouteRecordInfo<
      '/admin/operations/events/',
      '/admin/operations/events',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/operations/housekeeping/': RouteRecordInfo<
      '/admin/operations/housekeeping/',
      '/admin/operations/housekeeping',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/operations/maintenance/': RouteRecordInfo<
      '/admin/operations/maintenance/',
      '/admin/operations/maintenance',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/operations/notifications/': RouteRecordInfo<
      '/admin/operations/notifications/',
      '/admin/operations/notifications',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/operations/suppliers/': RouteRecordInfo<
      '/admin/operations/suppliers/',
      '/admin/operations/suppliers',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/property/': RouteRecordInfo<
      '/admin/property/',
      '/admin/property',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/property/access/': RouteRecordInfo<
      '/admin/property/access/',
      '/admin/property/access',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/property/availability/': RouteRecordInfo<
      '/admin/property/availability/',
      '/admin/property/availability',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/property/channel-manager/': RouteRecordInfo<
      '/admin/property/channel-manager/',
      '/admin/property/channel-manager',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/property/floors/': RouteRecordInfo<
      '/admin/property/floors/',
      '/admin/property/floors',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/property/halls/': RouteRecordInfo<
      '/admin/property/halls/',
      '/admin/property/halls',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/property/hotels/': RouteRecordInfo<
      '/admin/property/hotels/',
      '/admin/property/hotels',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/property/pricing/': RouteRecordInfo<
      '/admin/property/pricing/',
      '/admin/property/pricing',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/property/room-types/': RouteRecordInfo<
      '/admin/property/room-types/',
      '/admin/property/room-types',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/property/rooms/': RouteRecordInfo<
      '/admin/property/rooms/',
      '/admin/property/rooms',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/property/smart-tv/': RouteRecordInfo<
      '/admin/property/smart-tv/',
      '/admin/property/smart-tv',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/settings/': RouteRecordInfo<
      '/admin/settings/',
      '/admin/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/settings/billing': RouteRecordInfo<
      '/admin/settings/billing',
      '/admin/settings/billing',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/settings/notifications': RouteRecordInfo<
      '/admin/settings/notifications',
      '/admin/settings/notifications',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/settings/profile': RouteRecordInfo<
      '/admin/settings/profile',
      '/admin/settings/profile',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/settings/security': RouteRecordInfo<
      '/admin/settings/security',
      '/admin/settings/security',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/team/': RouteRecordInfo<
      '/admin/team/',
      '/admin/team',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/team/permissions/': RouteRecordInfo<
      '/admin/team/permissions/',
      '/admin/team/permissions',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/team/staff/': RouteRecordInfo<
      '/admin/team/staff/',
      '/admin/team/staff',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/contact': RouteRecordInfo<
      '/contact',
      '/contact',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard': RouteRecordInfo<
      '/dashboard',
      '/dashboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/faq': RouteRecordInfo<
      '/faq',
      '/faq',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/forgot-password': RouteRecordInfo<
      '/forgot-password',
      '/forgot-password',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/forgot-password-otp': RouteRecordInfo<
      '/forgot-password-otp',
      '/forgot-password-otp',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/otp': RouteRecordInfo<
      '/otp',
      '/otp',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/platform/': RouteRecordInfo<
      '/platform/',
      '/platform',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/platform/activity-logs/': RouteRecordInfo<
      '/platform/activity-logs/',
      '/platform/activity-logs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/platform/bookings/': RouteRecordInfo<
      '/platform/bookings/',
      '/platform/bookings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/platform/customers/': RouteRecordInfo<
      '/platform/customers/',
      '/platform/customers',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/platform/failed-jobs/': RouteRecordInfo<
      '/platform/failed-jobs/',
      '/platform/failed-jobs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/platform/hotels/': RouteRecordInfo<
      '/platform/hotels/',
      '/platform/hotels',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/platform/hotels/[id]': RouteRecordInfo<
      '/platform/hotels/[id]',
      '/platform/hotels/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/platform/invoices/': RouteRecordInfo<
      '/platform/invoices/',
      '/platform/invoices',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/platform/invoices/[id]': RouteRecordInfo<
      '/platform/invoices/[id]',
      '/platform/invoices/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/platform/locations/': RouteRecordInfo<
      '/platform/locations/',
      '/platform/locations',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/platform/locations/cities': RouteRecordInfo<
      '/platform/locations/cities',
      '/platform/locations/cities',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/platform/locations/states': RouteRecordInfo<
      '/platform/locations/states',
      '/platform/locations/states',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/platform/plans/': RouteRecordInfo<
      '/platform/plans/',
      '/platform/plans',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/platform/plans/[id]/': RouteRecordInfo<
      '/platform/plans/[id]/',
      '/platform/plans/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/platform/plans/[id]/edit': RouteRecordInfo<
      '/platform/plans/[id]/edit',
      '/platform/plans/:id/edit',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/platform/plans/new': RouteRecordInfo<
      '/platform/plans/new',
      '/platform/plans/new',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/platform/staff/': RouteRecordInfo<
      '/platform/staff/',
      '/platform/staff',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/platform/subscriptions/': RouteRecordInfo<
      '/platform/subscriptions/',
      '/platform/subscriptions',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/preview': RouteRecordInfo<
      '/preview',
      '/preview',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/reset-password': RouteRecordInfo<
      '/reset-password',
      '/reset-password',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/search': RouteRecordInfo<
      '/search',
      '/search',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sign-in': RouteRecordInfo<
      '/sign-in',
      '/sign-in',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sign-up': RouteRecordInfo<
      '/sign-up',
      '/sign-up',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/about.vue': {
      routes:
        | '/about'
      views:
        | never
    }
    'src/pages/admin/index.vue': {
      routes:
        | '/admin/'
      views:
        | never
    }
    'src/pages/admin/bookings/index.vue': {
      routes:
        | '/admin/bookings/'
      views:
        | never
    }
    'src/pages/admin/bookings/check-ins/index.vue': {
      routes:
        | '/admin/bookings/check-ins/'
      views:
        | never
    }
    'src/pages/admin/bookings/check-outs/index.vue': {
      routes:
        | '/admin/bookings/check-outs/'
      views:
        | never
    }
    'src/pages/admin/bookings/payments/index.vue': {
      routes:
        | '/admin/bookings/payments/'
      views:
        | never
    }
    'src/pages/admin/bookings/reservations/index.vue': {
      routes:
        | '/admin/bookings/reservations/'
      views:
        | never
    }
    'src/pages/admin/bookings/walk-ins/index.vue': {
      routes:
        | '/admin/bookings/walk-ins/'
      views:
        | never
    }
    'src/pages/admin/content/index.vue': {
      routes:
        | '/admin/content/'
      views:
        | never
    }
    'src/pages/admin/content/articles/index.vue': {
      routes:
        | '/admin/content/articles/'
      views:
        | never
    }
    'src/pages/admin/content/gallery/index.vue': {
      routes:
        | '/admin/content/gallery/'
      views:
        | never
    }
    'src/pages/admin/content/social-media/index.vue': {
      routes:
        | '/admin/content/social-media/'
      views:
        | never
    }
    'src/pages/admin/finance/index.vue': {
      routes:
        | '/admin/finance/'
      views:
        | never
    }
    'src/pages/admin/finance/banks/index.vue': {
      routes:
        | '/admin/finance/banks/'
      views:
        | never
    }
    'src/pages/admin/finance/charges/index.vue': {
      routes:
        | '/admin/finance/charges/'
      views:
        | never
    }
    'src/pages/admin/finance/expenditures/index.vue': {
      routes:
        | '/admin/finance/expenditures/'
      views:
        | never
    }
    'src/pages/admin/finance/hotel-gateways/index.vue': {
      routes:
        | '/admin/finance/hotel-gateways/'
      views:
        | never
    }
    'src/pages/admin/finance/invoices/index.vue': {
      routes:
        | '/admin/finance/invoices/'
      views:
        | never
    }
    'src/pages/admin/finance/payouts/index.vue': {
      routes:
        | '/admin/finance/payouts/'
      views:
        | never
    }
    'src/pages/admin/finance/pos/index.vue': {
      routes:
        | '/admin/finance/pos/'
      views:
        | never
    }
    'src/pages/admin/finance/refunds/index.vue': {
      routes:
        | '/admin/finance/refunds/'
      views:
        | never
    }
    'src/pages/admin/finance/revenues/index.vue': {
      routes:
        | '/admin/finance/revenues/'
      views:
        | never
    }
    'src/pages/admin/finance/sales/index.vue': {
      routes:
        | '/admin/finance/sales/'
      views:
        | never
    }
    'src/pages/admin/finance/subscriptions/index.vue': {
      routes:
        | '/admin/finance/subscriptions/'
      views:
        | never
    }
    'src/pages/admin/finance/virtual-accounts/index.vue': {
      routes:
        | '/admin/finance/virtual-accounts/'
      views:
        | never
    }
    'src/pages/admin/finance/vouchers/index.vue': {
      routes:
        | '/admin/finance/vouchers/'
      views:
        | never
    }
    'src/pages/admin/front-desk.vue': {
      routes:
        | '/admin/front-desk'
      views:
        | never
    }
    'src/pages/admin/guests/index.vue': {
      routes:
        | '/admin/guests/'
      views:
        | never
    }
    'src/pages/admin/guests/customers/index.vue': {
      routes:
        | '/admin/guests/customers/'
      views:
        | never
    }
    'src/pages/admin/guests/directory/index.vue': {
      routes:
        | '/admin/guests/directory/'
      views:
        | never
    }
    'src/pages/admin/guests/favourites/index.vue': {
      routes:
        | '/admin/guests/favourites/'
      views:
        | never
    }
    'src/pages/admin/guests/ratings/index.vue': {
      routes:
        | '/admin/guests/ratings/'
      views:
        | never
    }
    'src/pages/admin/guests/visitors/index.vue': {
      routes:
        | '/admin/guests/visitors/'
      views:
        | never
    }
    'src/pages/admin/insights/index.vue': {
      routes:
        | '/admin/insights/'
      views:
        | never
    }
    'src/pages/admin/insights/activity-logs/index.vue': {
      routes:
        | '/admin/insights/activity-logs/'
      views:
        | never
    }
    'src/pages/admin/insights/analytics/index.vue': {
      routes:
        | '/admin/insights/analytics/'
      views:
        | never
    }
    'src/pages/admin/insights/bookings/index.vue': {
      routes:
        | '/admin/insights/bookings/'
      views:
        | never
    }
    'src/pages/admin/insights/customers/index.vue': {
      routes:
        | '/admin/insights/customers/'
      views:
        | never
    }
    'src/pages/admin/insights/exports/index.vue': {
      routes:
        | '/admin/insights/exports/'
      views:
        | never
    }
    'src/pages/admin/insights/reports/index.vue': {
      routes:
        | '/admin/insights/reports/'
      views:
        | never
    }
    'src/pages/admin/insights/revenue-trends/index.vue': {
      routes:
        | '/admin/insights/revenue-trends/'
      views:
        | never
    }
    'src/pages/admin/operations/index.vue': {
      routes:
        | '/admin/operations/'
      views:
        | never
    }
    'src/pages/admin/operations/events/index.vue': {
      routes:
        | '/admin/operations/events/'
      views:
        | never
    }
    'src/pages/admin/operations/housekeeping/index.vue': {
      routes:
        | '/admin/operations/housekeeping/'
      views:
        | never
    }
    'src/pages/admin/operations/maintenance/index.vue': {
      routes:
        | '/admin/operations/maintenance/'
      views:
        | never
    }
    'src/pages/admin/operations/notifications/index.vue': {
      routes:
        | '/admin/operations/notifications/'
      views:
        | never
    }
    'src/pages/admin/operations/suppliers/index.vue': {
      routes:
        | '/admin/operations/suppliers/'
      views:
        | never
    }
    'src/pages/admin/property/index.vue': {
      routes:
        | '/admin/property/'
      views:
        | never
    }
    'src/pages/admin/property/access/index.vue': {
      routes:
        | '/admin/property/access/'
      views:
        | never
    }
    'src/pages/admin/property/availability/index.vue': {
      routes:
        | '/admin/property/availability/'
      views:
        | never
    }
    'src/pages/admin/property/channel-manager/index.vue': {
      routes:
        | '/admin/property/channel-manager/'
      views:
        | never
    }
    'src/pages/admin/property/floors/index.vue': {
      routes:
        | '/admin/property/floors/'
      views:
        | never
    }
    'src/pages/admin/property/halls/index.vue': {
      routes:
        | '/admin/property/halls/'
      views:
        | never
    }
    'src/pages/admin/property/hotels/index.vue': {
      routes:
        | '/admin/property/hotels/'
      views:
        | never
    }
    'src/pages/admin/property/pricing/index.vue': {
      routes:
        | '/admin/property/pricing/'
      views:
        | never
    }
    'src/pages/admin/property/room-types/index.vue': {
      routes:
        | '/admin/property/room-types/'
      views:
        | never
    }
    'src/pages/admin/property/rooms/index.vue': {
      routes:
        | '/admin/property/rooms/'
      views:
        | never
    }
    'src/pages/admin/property/smart-tv/index.vue': {
      routes:
        | '/admin/property/smart-tv/'
      views:
        | never
    }
    'src/pages/admin/settings/index.vue': {
      routes:
        | '/admin/settings/'
      views:
        | never
    }
    'src/pages/admin/settings/billing.vue': {
      routes:
        | '/admin/settings/billing'
      views:
        | never
    }
    'src/pages/admin/settings/notifications.vue': {
      routes:
        | '/admin/settings/notifications'
      views:
        | never
    }
    'src/pages/admin/settings/profile.vue': {
      routes:
        | '/admin/settings/profile'
      views:
        | never
    }
    'src/pages/admin/settings/security.vue': {
      routes:
        | '/admin/settings/security'
      views:
        | never
    }
    'src/pages/admin/team/index.vue': {
      routes:
        | '/admin/team/'
      views:
        | never
    }
    'src/pages/admin/team/permissions/index.vue': {
      routes:
        | '/admin/team/permissions/'
      views:
        | never
    }
    'src/pages/admin/team/staff/index.vue': {
      routes:
        | '/admin/team/staff/'
      views:
        | never
    }
    'src/pages/contact.vue': {
      routes:
        | '/contact'
      views:
        | never
    }
    'src/pages/dashboard.vue': {
      routes:
        | '/dashboard'
      views:
        | never
    }
    'src/pages/faq.vue': {
      routes:
        | '/faq'
      views:
        | never
    }
    'src/pages/forgot-password.vue': {
      routes:
        | '/forgot-password'
      views:
        | never
    }
    'src/pages/forgot-password-otp.vue': {
      routes:
        | '/forgot-password-otp'
      views:
        | never
    }
    'src/pages/otp.vue': {
      routes:
        | '/otp'
      views:
        | never
    }
    'src/pages/platform/index.vue': {
      routes:
        | '/platform/'
      views:
        | never
    }
    'src/pages/platform/activity-logs/index.vue': {
      routes:
        | '/platform/activity-logs/'
      views:
        | never
    }
    'src/pages/platform/bookings/index.vue': {
      routes:
        | '/platform/bookings/'
      views:
        | never
    }
    'src/pages/platform/customers/index.vue': {
      routes:
        | '/platform/customers/'
      views:
        | never
    }
    'src/pages/platform/failed-jobs/index.vue': {
      routes:
        | '/platform/failed-jobs/'
      views:
        | never
    }
    'src/pages/platform/hotels/index.vue': {
      routes:
        | '/platform/hotels/'
      views:
        | never
    }
    'src/pages/platform/hotels/[id].vue': {
      routes:
        | '/platform/hotels/[id]'
      views:
        | never
    }
    'src/pages/platform/invoices/index.vue': {
      routes:
        | '/platform/invoices/'
      views:
        | never
    }
    'src/pages/platform/invoices/[id].vue': {
      routes:
        | '/platform/invoices/[id]'
      views:
        | never
    }
    'src/pages/platform/locations/index.vue': {
      routes:
        | '/platform/locations/'
      views:
        | never
    }
    'src/pages/platform/locations/cities.vue': {
      routes:
        | '/platform/locations/cities'
      views:
        | never
    }
    'src/pages/platform/locations/states.vue': {
      routes:
        | '/platform/locations/states'
      views:
        | never
    }
    'src/pages/platform/plans/index.vue': {
      routes:
        | '/platform/plans/'
      views:
        | never
    }
    'src/pages/platform/plans/[id]/index.vue': {
      routes:
        | '/platform/plans/[id]/'
      views:
        | never
    }
    'src/pages/platform/plans/[id]/edit.vue': {
      routes:
        | '/platform/plans/[id]/edit'
      views:
        | never
    }
    'src/pages/platform/plans/new.vue': {
      routes:
        | '/platform/plans/new'
      views:
        | never
    }
    'src/pages/platform/staff/index.vue': {
      routes:
        | '/platform/staff/'
      views:
        | never
    }
    'src/pages/platform/subscriptions/index.vue': {
      routes:
        | '/platform/subscriptions/'
      views:
        | never
    }
    'src/pages/preview.vue': {
      routes:
        | '/preview'
      views:
        | never
    }
    'src/pages/reset-password.vue': {
      routes:
        | '/reset-password'
      views:
        | never
    }
    'src/pages/search.vue': {
      routes:
        | '/search'
      views:
        | never
    }
    'src/pages/sign-in.vue': {
      routes:
        | '/sign-in'
      views:
        | never
    }
    'src/pages/sign-up.vue': {
      routes:
        | '/sign-up'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
